### ISSUE TITLE
FPS output

### ISSUE THREAD

**Issue by cl3m3nt** [surfriderfoundationeurope/surfnet#3]
Dear @charlesollion, 

the surfnet output does not provide the video FPS which is needed by subsequent ETL plastic origin processing.
Like MOT, could you please add this data to surfnet output ? See example below.

{
    "detected_trash": [...],
    "fps": 4,
    "video_id": "tmp_28022020_Boudigau_4_short_480.mov",
    "video_length": 45
}

**Comment by charlesollion** [comment]
Hello @cl3m3nt do you want only the fps, or also the id and length?

**Comment by charlesollion** [comment]
@cl3m3nt Pushed a new version with updates. You may close this issue once you confirm the format is the one you want. Here length = #of frames in video / (skip_frames + 1)

**Comment by cl3m3nt** [comment]
Tx it works like a charm.
Closing the issue.
